name: TranceTeams
main: com.c45y.tranceteams.TranceTeams
version: 0.1
softdepend: [Multiverse-Core]
permissions:
    tranceteams.user:
        description: A player
        default: true
    tranceteams.op:
        description: A admin type player
        default: op
commands:
  team:
    description: Basic command
    permission: tranceteams.user
    usage: |
           /team: [one, two]
  teamadmin:
    description: Basic admin command
    permission: tranceteams.op
    usage: |
           /teamadmin: [one, two]